### ISSUE TITLE
Formatting nits

### ISSUE THREAD

**Issue by domenic** [ricea/encoding-streams#2]
In the DOM intro, TextDecoder should be monospace and link to the TextDecoder constructor.

RangeError and TypeError should link throughout.

TransformStream and ReadableStream should be monospace and link throughout. (Although TransformStream doesn't have anywhere to link to yet, so I guess disregard that part.)

Uint8Array and ArrayBuffer should link.

In "UTF-8's encoder", both "UTF-8" and "encoder" should link.

**Comment by domenic** [comment]
I guess for a lot of the "should link", the existing spec does not, so those can be disregarded.

**Comment by ricea** [comment]
The streams and ecmascript cross-references are awkward with anolis. If I can get my local hacks accepted into the xref repository, then it will work. Otherwise I will have to take them out again before merging to upstream. I made TransformStream link to the mostly-empty section in the spec :smile:.

**Comment by ricea** [comment]
Done.
